name: gitearn

services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
        - VITE_API_URL=https://${DOMAIN?Variable not set}
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/gitearn

